import { defineConfig } from "oxlint";

export default defineConfig({
  ignorePatterns: ["node_modules"],
  jsPlugins: [
    { name: "plumb", specifier: "./src/index.ts" },
    { name: "plumb-meta", specifier: "./src/meta/index.ts" },
    { name: "plumb-effect", specifier: "./src/effect/index.ts" },
  ],
  rules: {
    "plumb/no-builtin-throws": "warn",
    "plumb/no-barrel-export-star": "warn",
    "plumb/no-generic-export-names": "warn",
    "plumb/no-swappable-primitive-params": "warn",
    "plumb/no-transposed-field-reads": "warn",
    "plumb/no-vague-test-filenames": "warn",
    "plumb/no-chained-type-assertions": "warn",
    "plumb/no-conditional-empty-object-spread": "warn",
    "plumb/no-impossible-branch-throw": "warn",
    "plumb/no-known-value-widening": "warn",
    "plumb/no-module-mocking": "warn",
    "plumb/no-object-parameters": "warn",
    "plumb/no-product-of-state-booleans": "warn",
    "plumb/no-reflect-apply": "warn",
    "plumb/no-reflect-get": "warn",
    "plumb/no-runtime-typeof": "warn",
    "plumb/no-sentinel-comparison-union": "warn",
    "plumb/no-stray-inline-comments": "warn",
    "plumb/no-tag-ladder-assertions": "warn",
    "plumb/no-redundant-derived-field": "warn",
    "plumb/no-nondeterministic-core": "warn",
    "plumb/no-exported-mutable-state": "warn",
    "plumb/no-anonymous-wide-tuples": "warn",
    "plumb/no-duplicated-literal-union": "warn",
    "plumb/require-canonical-stringify-for-identity": "warn",
    "plumb/require-sort-comparator": "warn",
    "plumb/require-exhaustive-tag-switch": "warn",
    "plumb/no-shape-in-symbol-names": "warn",
    "plumb/no-unknown-parameters": "warn",
    "plumb/no-unknown-returns": "warn",
    "plumb/no-unknown-type-aliases": "warn",
    "plumb/no-unit-return-validators": "warn",
    "plumb/no-unsafe-dictionary-type": "warn",
    "plumb/no-widen-then-assert": "warn",
    "plumb/no-stacked-jsdoc-blocks": "warn",
    "plumb/prefer-payload-brand": "warn",
    "plumb/require-fc-block-predicate": "warn",
    "plumb/require-jsdoc-on-exported": "warn",
    "plumb/require-published-order": "warn",
    "plumb/require-safety-comment-for-type-assertion": "warn",
    "plumb/prefer-property-tests": "warn",
    "plumb-effect/guarded-op-must-return-effect": "warn",
    "plumb-effect/guarded-op-must-return-option": "warn",
    "plumb-effect/no-decode-unknown-option": "warn",
    "plumb-effect/no-schema-class-modeling": "warn",
    "plumb-effect/no-service-constructor-imports": "warn",
    "plumb-effect/prefer-effect-predicate-over-boolean-function": "warn",
    "plumb-effect/prefer-named-guard-predicate": "warn",
    "plumb-effect/prefer-option-pipeline": "warn",
    "plumb-effect/prefer-ordering-match": "warn",
    "plumb-effect/prefer-tagged-enum": "warn",
    "plumb-effect/require-schema-type-derivation": "warn",
    "plumb-effect/no-unguarded-json-parse": "warn",
    "plumb-effect/no-manual-field-guards": "warn",
    "plumb-effect/option-core-needs-effect-public": "warn",
    "plumb-effect/prefer-die-for-precondition-defects": "warn",
    "plumb-effect/prefer-effect-gen-for-guard-ladders": "warn",
    "plumb-meta/no-manual-ancestor-walks": "warn",
    "plumb-meta/prefer-before-file-scope": "warn",
    "plumb-meta/require-create-once": "warn",
    "plumb-meta/require-rule-tester": "warn",
  },
  overrides: [
    { files: ["src/**/*.ts"], rules: { "unicorn/prefer-string-starts-ends-with": "off", "eslint/no-unused-vars": "off" } },
  ],
});
